### PR TITLE
Display content as a popup or as a new tab

### PR DESCRIPTION
**Pull request by Corpella**
I added a section to the extension's option page that allows the user to choose whether to display the clicked search element as a new tab or popup. Currently, the popup window is fixed in size and opens on the left side of the screen. However, in the future, It could be useful to add more customizable settings that would allow the user to choose the exact width and height of the popup window.

My code may not be following React's best practices, or it may not be good at all since I am not experienced in React development, but I wanted to contribute to this project as it is a really useful and well written extension.

### CODE REVIEW

**Comment by Cside** [comment]
Thank you for the good code.
But I'm afraid I cannot accept your code. This is because it's my policy not to add features that the original notion search does not have.
From the next time, instead of sending a pull request first,  it would be great if you could create an Issue first and discuss it with me.

**Comment by Corpella** [comment]
@C

**Comment by Corpella** [comment]
@Cside t

**Comment by Corpella** [comment]
@Cside Thank you for the reply.
I was thinking about opening an issue about this, but I thought it would be disrespectful to ask for a new feature without trying to at least help. 

I think this could be a useful feature and if you want to implement this in the future with proper code and tests that would be awesome

**Comment by Cside** [comment]
Okay.
I'll close this pull request, but if I decide to implement the feature in the future, I'll use your awesome code!

**Pull request closed without merging**
